name: CI Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run build script
        run: |
          chmod +x ./build.sh
          ./build.sh


      - name: Deploy to Kubernetes
        run: |
          mkdir -p $HOME/.kube
          echo ${{ secrets.KUBECONFIG }} | base64 -d > $HOME/.kube/config
          kubectl rollout restart deployment/ltnc-frontend
